export const GetMockResponse = async () => ({
  data: {
    result: {
      data: [
        {
          location_id: "17788780",
          name: "Mega Light Hotel",
          latitude: "12.25718",
          longitude: "109.13179",
          num_reviews: "2",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Nha Trang, Khanh Hoa Province",
          photo: {
            images: {
              small: {
                width: "150",
                url: "https://media-cdn.tripadvisor.com/media/photo-l/1b/50/04/c7/mega-light-hotel.jpg",
                height: "150",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/photo-t/1b/50/04/c7/mega-light-hotel.jpg",
                height: "50",
              },
              original: {
                width: "2880",
                url: "https://media-cdn.tripadvisor.com/media/photo-o/1b/50/04/c7/mega-light-hotel.jpg",
                height: "2025",
              },
              large: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/photo-s/1b/50/04/c7/mega-light-hotel.jpg",
                height: "387",
              },
              medium: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/photo-f/1b/50/04/c7/mega-light-hotel.jpg",
                height: "176",
              },
            },
            is_blessed: true,
            uploaded_date: "2020-05-09T00:47:37-0400",
            caption: "",
            id: "458228935",
            helpful_votes: "0",
            published_date: "2020-05-09T00:47:37-0400",
            user: {
              user_id: null,
              member_id: "0",
              type: "user",
            },
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          raw_ranking: "3.066725492477417",
          ranking_geo: "Nha Trang",
          ranking_geo_id: "293928",
          ranking_position: "1",
          ranking_denominator: "1608",
          ranking_category: "hotel",
          ranking: "#1 Best Value of 1,608 places to stay in Nha Trang",
          subcategory_type: "hotel",
          subcategory_type_label: "Hotel",
          distance: "22.460704577310636",
          distance_string: null,
          bearing: "east",
          rating: "5.0",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$10 - $24",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "6a0fd4a8-0b5f-4cf0-8607-057adbc1b875",
        },
        {
          location_id: "16667354",
          name: "Chappi Mountains Homestay Bungalows & Coffee Resting Station",
          latitude: "12.140835",
          longitude: "108.631775",
          num_reviews: "4",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Lac Duong, Lam Dong Province",
          photo: {
            images: {
              small: {
                width: "150",
                url: "https://media-cdn.tripadvisor.com/media/photo-l/17/02/4b/1c/chappi-mountains-resort.jpg",
                height: "150",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/photo-t/17/02/4b/1c/chappi-mountains-resort.jpg",
                height: "50",
              },
              original: {
                width: "4032",
                url: "https://media-cdn.tripadvisor.com/media/photo-o/17/02/4b/1c/chappi-mountains-resort.jpg",
                height: "3024",
              },
              large: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/photo-s/17/02/4b/1c/chappi-mountains-resort.jpg",
                height: "412",
              },
              medium: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/photo-f/17/02/4b/1c/chappi-mountains-resort.jpg",
                height: "188",
              },
            },
            is_blessed: true,
            uploaded_date: "2019-03-31T23:17:35-0400",
            caption: "",
            id: "386026268",
            helpful_votes: "0",
            published_date: "2019-03-31T23:17:35-0400",
            user: {
              user_id: null,
              member_id: "0",
              type: "user",
            },
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          raw_ranking: "3.093738317489624",
          ranking_geo: "Lac Duong",
          ranking_geo_id: "14759657",
          ranking_position: "2",
          ranking_denominator: "1608",
          ranking_category: "bb",
          ranking: "#2 Best Value of 1,608 places to stay in Nha Trang",
          subcategory_type: "small_hotel",
          subcategory_type_label: "Small Hotel",
          distance: "18.517496440446912",
          distance_string: null,
          bearing: "southwest",
          rating: "4.5",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$21 - $28",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "534bc2df-7b43-4176-99ec-da9440a174f7",
        },
        {
          location_id: "21106942",
          name: "OYO 995 Tan Thanh Dat Hotel",
          latitude: "12.47471",
          longitude: "109.12265",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Nha Trang, Khanh Hoa Province",
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "3",
          ranking_denominator: "1608",
          ranking: "#3 Best Value of 1,608 places to stay in Nha Trang",
          distance: "22.92105530894745",
          distance_string: null,
          bearing: "northeast",
          is_closed: false,
          is_long_closed: false,
          price_level: "",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "5432606f-cf54-4930-8998-b4f3618546d3",
        },
        {
          location_id: "19617410",
          name: "Ba Ho Eco Resort",
          latitude: "12.390017",
          longitude: "109.137924",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Ninh Hoa, Khanh Hoa Province",
          photo: {
            images: {
              small: {
                width: "150",
                url: "https://media-cdn.tripadvisor.com/media/photo-l/1b/10/bc/6b/caption.jpg",
                height: "150",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/photo-t/1b/10/bc/6b/caption.jpg",
                height: "50",
              },
              original: {
                width: "1280",
                url: "https://media-cdn.tripadvisor.com/media/photo-m/1280/1b/10/bc/6b/caption.jpg",
                height: "1280",
              },
              large: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/photo-p/1b/10/bc/6b/caption.jpg",
                height: "550",
              },
              medium: {
                width: "450",
                url: "https://media-cdn.tripadvisor.com/media/photo-s/1b/10/bc/6b/caption.jpg",
                height: "450",
              },
            },
            is_blessed: true,
            uploaded_date: "2020-03-02T23:59:41-0500",
            caption:
              "Водопады Ба Хо обязательны к посещению . Ехать с утра и на весь день . Здесь есть все необходимое для отдыха - катамараны , лодочки и тд....ресторан с вкусной и недорогой едой  ! Можно подняться на три  ступени водопадов , в каждом водоём , можно искупаться и сделать пилинг рыбками. Ребята прыгали даже со скал , я не рискнула ))",
            id: "454081643",
            helpful_votes: "0",
            published_date: "2020-03-02T23:59:41-0500",
            user: {
              user_id: null,
              member_id: "0",
              type: "user",
            },
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "4",
          ranking_denominator: "1608",
          ranking: "#4 Best Value of 1,608 places to stay in Nha Trang",
          distance: "22.307619839416027",
          distance_string: null,
          bearing: "east",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$42 - $53",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "0f750233-42d4-4af1-be11-1b58d60bce33",
        },
        {
          location_id: "12791381",
          name: "Anh Hao Hotel",
          latitude: "12.492512",
          longitude: "109.125656",
          num_reviews: "1",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Ninh Hoa, Khanh Hoa Province",
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          raw_ranking: "3.026113986968994",
          ranking_geo: "Ninh Hoa",
          ranking_geo_id: "12920594",
          ranking_position: "5",
          ranking_denominator: "1608",
          ranking_category: "bb",
          ranking: "#5 Best Value of 1,608 places to stay in Nha Trang",
          subcategory_type: "inn",
          subcategory_type_label: "Inn",
          distance: "23.61926745486276",
          distance_string: null,
          bearing: "northeast",
          rating: "5.0",
          is_closed: false,
          is_long_closed: false,
          price_level: "",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "f53823d9-c616-41e8-97cd-d5bebe876f47",
        },
        {
          location_id: "23268427",
          name: "Nha nghi Huong Thom",
          latitude: "12.151361",
          longitude: "109.07109",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Ninh Hoa, Khanh Hoa Province",
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "6",
          ranking_denominator: "1608",
          ranking: "#6 Best Value of 1,608 places to stay in Nha Trang",
          distance: "22.005794900088333",
          distance_string: null,
          bearing: "southeast",
          is_closed: false,
          is_long_closed: false,
          price_level: "",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "b563533a-9cf5-4438-acc0-290adb47b8c8",
        },
        {
          location_id: "293928",
          ad_position: "inline1",
          ad_size: "8X8",
          doubleclick_zone: "as.vietnam.khanh_hoa.nha_trang",
          ancestors: [
            {
              subcategory: [
                {
                  key: "province",
                  name: "Province",
                },
              ],
              name: "Khanh Hoa Province",
              abbrv: null,
              location_id: "1184689",
            },
            {
              subcategory: [
                {
                  key: "country",
                  name: "Country",
                },
              ],
              name: "Vietnam",
              abbrv: null,
              location_id: "293921",
            },
          ],
          detail: "0",
          page_type: "hotels",
          mob_ptype: "app_hotels",
        },
        {
          location_id: "15011691",
          name: "Misa Guesthouse",
          latitude: "12.25585",
          longitude: "109.09402",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Dien Khanh, Khanh Hoa Province",
          photo: {
            images: {
              small: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/19/ab/66/7f/facadeentrance.jpg",
                height: "137",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/19/ab/66/7f/facadeentrance.jpg",
                height: "50",
              },
              original: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/ab/66/7f/facadeentrance.jpg",
                height: "460",
              },
              large: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/ab/66/7f/facadeentrance.jpg",
                height: "460",
              },
              medium: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/19/ab/66/7f/facadeentrance.jpg",
                height: "301",
              },
            },
            is_blessed: true,
            uploaded_date: "2019-10-17T11:31:13-0400",
            caption: "Facade/entrance",
            id: "430663295",
            helpful_votes: "0",
            published_date: "2019-10-17T11:31:13-0400",
            user: null,
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "7",
          ranking_denominator: "1608",
          ranking: "#7 Best Value of 1,608 places to stay in Nha Trang",
          distance: "20.037750020437375",
          distance_string: null,
          bearing: "east",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$12",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "6f8568c2-243d-4d3c-b101-d889d601fe05",
        },
        {
          location_id: "15321078",
          name: "Diagon Alley Homestay",
          latitude: "12.260297",
          longitude: "109.14451",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Nha Trang, Khanh Hoa Province",
          photo: {
            images: {
              small: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/19/b6/f5/aa/2715551.jpg",
                height: "137",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/19/b6/f5/aa/2715551.jpg",
                height: "50",
              },
              original: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/b6/f5/aa/2715551.jpg",
                height: "460",
              },
              large: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/b6/f5/aa/2715551.jpg",
                height: "460",
              },
              medium: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/19/b6/f5/aa/2715551.jpg",
                height: "301",
              },
            },
            is_blessed: true,
            uploaded_date: "2019-10-17T19:16:45-0400",
            caption: "Diagon Alley Homestay",
            id: "431420842",
            helpful_votes: "0",
            published_date: "2019-10-17T19:16:45-0400",
            user: null,
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "8",
          ranking_denominator: "1608",
          ranking: "#8 Best Value of 1,608 places to stay in Nha Trang",
          distance: "23.236559140207984",
          distance_string: null,
          bearing: "east",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$23 - $38",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "92708045-3074-487c-827f-0c8b8644825b",
        },
        {
          location_id: "1114960",
          name: "Memento Country Home Resort",
          latitude: "12.252621",
          longitude: "109.06524",
          num_reviews: "30",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Nha Trang, Khanh Hoa Province",
          photo: {
            images: {
              small: {
                width: "150",
                url: "https://media-cdn.tripadvisor.com/media/photo-l/0a/51/0c/eb/the-mainson.jpg",
                height: "150",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/photo-t/0a/51/0c/eb/the-mainson.jpg",
                height: "50",
              },
              original: {
                width: "1000",
                url: "https://media-cdn.tripadvisor.com/media/photo-o/0a/51/0c/eb/the-mainson.jpg",
                height: "562",
              },
              large: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/photo-s/0a/51/0c/eb/the-mainson.jpg",
                height: "309",
              },
              medium: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/photo-f/0a/51/0c/eb/the-mainson.jpg",
                height: "141",
              },
            },
            is_blessed: true,
            uploaded_date: "2016-02-13T20:46:01-0500",
            caption: "The Mainson",
            id: "173083883",
            helpful_votes: "0",
            published_date: "2016-02-13T20:46:01-0500",
            user: {
              user_id: null,
              member_id: "0",
              type: "user",
            },
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          raw_ranking: "3.198458433151245",
          ranking_geo: "Nha Trang",
          ranking_geo_id: "293928",
          ranking_position: "9",
          ranking_denominator: "1608",
          ranking_category: "bb",
          ranking: "#9 Best Value of 1,608 places to stay in Nha Trang",
          subcategory_type: "small_hotel",
          subcategory_type_label: "Small Hotel",
          distance: "18.26787737328682",
          distance_string: null,
          bearing: "east",
          rating: "4.0",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$20 - $25",
          hotel_class: "3.0",
          hotel_class_attribution:
            "This property is classified according to Giata.",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "66668d0a-a05b-44f7-a2e1-52dafd050d67",
        },
        {
          location_id: "17638605",
          name: "Guest House Thanh Binh",
          latitude: "12.28163",
          longitude: "108.92137",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Khanh Vinh, Khanh Hoa Province",
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "10",
          ranking_denominator: "1608",
          ranking: "#10 Best Value of 1,608 places to stay in Nha Trang",
          distance: "8.567854322550199",
          distance_string: null,
          bearing: "southeast",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$14",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "453e7ed4-27b6-4309-bdd4-7a29064e6f60",
        },
        {
          location_id: "15574313",
          name: "Farmer's Resort",
          latitude: "12.26634",
          longitude: "108.99182",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Dien Thọ, Khanh Hoa Province",
          photo: {
            images: {
              small: {
                width: "150",
                url: "https://media-cdn.tripadvisor.com/media/photo-l/16/a2/13/c4/across-river.jpg",
                height: "150",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/photo-t/16/a2/13/c4/across-river.jpg",
                height: "50",
              },
              original: {
                width: "1280",
                url: "https://media-cdn.tripadvisor.com/media/photo-o/16/a2/13/c4/across-river.jpg",
                height: "960",
              },
              large: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/photo-s/16/a2/13/c4/across-river.jpg",
                height: "413",
              },
              medium: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/photo-f/16/a2/13/c4/across-river.jpg",
                height: "188",
              },
            },
            is_blessed: true,
            uploaded_date: "2019-03-02T10:12:31-0500",
            caption: "across river",
            id: "379720644",
            helpful_votes: "0",
            published_date: "2019-03-02T10:12:31-0500",
            user: {
              user_id: null,
              member_id: "0",
              type: "user",
            },
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "11",
          ranking_denominator: "1608",
          ranking: "#11 Best Value of 1,608 places to stay in Nha Trang",
          distance: "13.305339743048233",
          distance_string: null,
          bearing: "southeast",
          is_closed: false,
          is_long_closed: false,
          price_level: "",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "68fc7db0-42ed-436a-9c28-a63cf289dfa5",
        },
        {
          location_id: "20362856",
          name: "OYO 1015 Bon Mua Hotel",
          latitude: "12.25979",
          longitude: "109.11334",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Nha Trang, Khanh Hoa Province",
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "12",
          ranking_denominator: "1608",
          ranking: "#12 Best Value of 1,608 places to stay in Nha Trang",
          distance: "21.21106684791797",
          distance_string: null,
          bearing: "east",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$14 - $34",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "9ad95a69-6ee6-48b6-a3a8-e809c90ac4c1",
        },
        {
          location_id: "17707459",
          name: "Casa Blanca Villas",
          latitude: "12.259272",
          longitude: "109.1431",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Nha Trang, Khanh Hoa Province",
          photo: {
            images: {
              small: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/21/e4/e0/d2/caption.jpg",
                height: "137",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/21/e4/e0/d2/caption.jpg",
                height: "50",
              },
              original: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/21/e4/e0/d2/caption.jpg",
                height: "460",
              },
              large: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/21/e4/e0/d2/caption.jpg",
                height: "460",
              },
              medium: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/21/e4/e0/d2/caption.jpg",
                height: "301",
              },
            },
            is_blessed: true,
            uploaded_date: "2022-01-18T00:27:57-0500",
            caption: "",
            id: "568647890",
            helpful_votes: "0",
            published_date: "2022-01-18T00:27:57-0500",
            user: null,
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "13",
          ranking_denominator: "1608",
          ranking: "#13 Best Value of 1,608 places to stay in Nha Trang",
          distance: "23.16180801461108",
          distance_string: null,
          bearing: "east",
          is_closed: false,
          is_long_closed: false,
          price_level: "$$$$",
          price: "$232 - $664",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "0c469030-8c2f-4588-82b8-cb87f876ed26",
        },
        {
          location_id: "21504434",
          name: "Bao My Hotel",
          latitude: "12.486257",
          longitude: "109.12736",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Ninh Hiep, Ninh Hoa, Khanh Hoa Province",
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "14",
          ranking_denominator: "1608",
          ranking: "#14 Best Value of 1,608 places to stay in Nha Trang",
          distance: "23.537567114872367",
          distance_string: null,
          bearing: "northeast",
          is_closed: false,
          is_long_closed: false,
          price_level: "",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "b920a5c9-e85e-4470-8456-f701965c5ef7",
        },
        {
          location_id: "15353817",
          name: "Homestay Da Blah",
          latitude: "12.105029",
          longitude: "108.55508",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Lac Duong, Lam Dong Province",
          photo: {
            images: {
              small: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/1b/5d/12/0f/3936219.jpg",
                height: "137",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/1b/5d/12/0f/3936219.jpg",
                height: "50",
              },
              original: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1b/5d/12/0f/3936219.jpg",
                height: "460",
              },
              large: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1b/5d/12/0f/3936219.jpg",
                height: "460",
              },
              medium: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/1b/5d/12/0f/3936219.jpg",
                height: "301",
              },
            },
            is_blessed: true,
            uploaded_date: "2020-05-30T23:16:35-0400",
            caption: "Homestay Da Blah",
            id: "459084303",
            helpful_votes: "0",
            published_date: "2020-05-30T23:16:35-0400",
            user: null,
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "15",
          ranking_denominator: "1608",
          ranking: "#15 Best Value of 1,608 places to stay in Nha Trang",
          distance: "23.896876731770504",
          distance_string: null,
          bearing: "southwest",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$11 - $12",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "f219cd37-e3ee-401e-9782-b73070efda74",
        },
        {
          location_id: "18261033",
          name: "Nha Khach Vuon Quoc Gia Bidoup - Nui Ba",
          latitude: "12.105029",
          longitude: "108.55508",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Da Nhim, Lam Dong Province",
          photo: {
            images: {
              small: {
                width: "250",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/19/a8/f1/5c/4892278.jpg",
                height: "137",
              },
              thumbnail: {
                width: "50",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/19/a8/f1/5c/4892278.jpg",
                height: "50",
              },
              original: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/a8/f1/5c/4892278.jpg",
                height: "460",
              },
              large: {
                width: "840",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/a8/f1/5c/4892278.jpg",
                height: "460",
              },
              medium: {
                width: "550",
                url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/19/a8/f1/5c/4892278.jpg",
                height: "301",
              },
            },
            is_blessed: true,
            uploaded_date: "2019-10-17T05:35:54-0400",
            caption: "Nha Khach Vuon Quoc Gia Bidoup - Nui Ba",
            id: "430502236",
            helpful_votes: "0",
            published_date: "2019-10-17T05:35:54-0400",
            user: null,
          },
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "16",
          ranking_denominator: "1608",
          ranking: "#16 Best Value of 1,608 places to stay in Nha Trang",
          distance: "23.896876731770504",
          distance_string: null,
          bearing: "southwest",
          is_closed: false,
          is_long_closed: false,
          price_level: "$",
          price: "$19",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "d6efd14d-c916-45f4-acd9-4563624f4d9e",
        },
        {
          location_id: "17537513",
          name: "Junglebeach",
          latitude: "12.49512",
          longitude: "109.13291",
          num_reviews: "0",
          timezone: "Asia/Ho_Chi_Minh",
          location_string: "Ninh Hoa, Khanh Hoa Province",
          awards: [],
          preferred_map_engine: "default",
          autobroaden_type: "category_integrated",
          autobroaden_label: "Nha Trang Places to Stay",
          ranking_position: "17",
          ranking_denominator: "1608",
          ranking: "#17 Best Value of 1,608 places to stay in Nha Trang",
          distance: "24.13888025704297",
          distance_string: null,
          bearing: "northeast",
          is_closed: false,
          is_long_closed: false,
          price_level: "",
          hotel_class: "0.0",
          business_listings: {
            desktop_contacts: [],
            mobile_contacts: [],
          },
          special_offers: {
            desktop: [],
            mobile: [],
          },
          listing_key: "91ae1ae0-4e56-49ba-83d0-f7d28425b188",
        },
      ],
      status: {
        unfiltered_total_size: "17",
        commerce_country_iso_code: "US",
        autobroadened: true,
        progress: "100",
        auction_key: "2cbb6d256f2a43b5aeacc954f6909b24",
        primary_geo: "293928",
        pricing: "base",
        doubleClickZone: "as.vietnam.khanh_hoa.nha_trang",
      },
      paging: {
        results: "17",
        total_results: "17",
      },
    },
  },
  status: 200,
  statusText: "OK",
  headers: {
    connection: "keep-alive",
    "content-encoding": "gzip",
    "content-type": "application/json; charset=utf-8",
    date: "Wed, 19 Jan 2022 23:50:40 GMT",
    etag: '"60a7-tfdYyuLiItYDClolieqpe5Vi1Xk"',
    "keep-alive": "timeout=5",
    "transfer-encoding": "chunked",
    vary: "Accept-Encoding",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      Accept: "application/json, text/plain, */*",
    },
    method: "get",
    url: "/api/search?city=new%20york",
  },
  request: {},
});
